server:
  port: 8899
spring:
  datasource:
    url: jdbc:postgresql://10.100.51.202:5432/ruleengine?currentSchema=ruleengine_opr&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ruleengine_opr
    password: ruleengine_5152
    driver-class-name: org.postgresql.Driver
    minmumIdle: 1
    maxmumPoolSize: 2
    maxLifeTime: 1800000
    leakDetectionThreshold: 20000
  mvc:
    #出现错误时，直接抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射
    add-mappings: false

mybatis-plus:
  type-aliases-package: com.example.springbootdemo.entity
  mapper-locations: classpath:/mapper/*.xml